// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentSystem.Persistence;

namespace PaymentSystem.Persistence.Migrations
{
    [DbContext(typeof(PaymentSystemContext))]
    [Migration("20210910044414_Sample")]
    partial class Sample
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaymentSystem.Domain.Entities.Account", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            AccountNumber = 2123123,
                            Balance = 1200m,
                            Name = "Peter Parker"
                        },
                        new
                        {
                            ID = 2L,
                            AccountNumber = 65456453,
                            Balance = 2000m,
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("PaymentSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AccountID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            AccountID = 1L,
                            Amount = 1000m,
                            Date = new DateTime(2021, 9, 10, 12, 44, 14, 133, DateTimeKind.Local).AddTicks(7954),
                            Reason = "some reason",
                            Status = "Close"
                        },
                        new
                        {
                            ID = 2L,
                            AccountID = 1L,
                            Amount = 5000m,
                            Date = new DateTime(2021, 9, 10, 12, 44, 14, 134, DateTimeKind.Local).AddTicks(8232),
                            Reason = "",
                            Status = "Close"
                        },
                        new
                        {
                            ID = 3L,
                            AccountID = 2L,
                            Amount = 500m,
                            Date = new DateTime(2021, 9, 10, 12, 44, 14, 134, DateTimeKind.Local).AddTicks(8264),
                            Reason = "some reason",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("PaymentSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("PaymentSystem.Domain.Entities.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PaymentSystem.Domain.Entities.Account", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
